MicroRabbit.Presentation.App/Controllers/HomePageController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using MicroRabbit.Presentation.App.Application.Interfaces;
using MicroRabbit.Presentation.App.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MicroRabbit.Presentation.App.Controllers
{
    public class HomePageController : Controller
    {
        private readonly IRequestService _requestService;

        public HomePageController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTransfer(TransferViewModel viewModel)
        {
            var model = JsonConvert.SerializeObject(viewModel);

            await _requestService.SendRequest("https://localhost:9000/Banking/CreateTransaction", model);

            return View("Index");
        }
    }
}

MicroRabbit.Presentation.App/Views/HomePage/Index.cshtml
@model TransferViewModel
    <form asp-controller="HomePage" asp-action="CreateTransfer">
        <label asp-for="FormAccount">Input from account</label>
        <input asp-for="FormAccount" />
        <label asp-for="ToAccount">Input to account</label>
        <input asp-for="ToAccount" />
        <label asp-for="Amount">Input total amount</label>
        <input asp-for="Amount" />
        <input type="submit" />
    </form>

MicroRabbit.Presentation.App/Views/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    @RenderBody()
</body>
</html>